export const allProducts = [
  {
    id: "1",
    name: "لباس دخترانه",
    category: "girl",
    description: "لباس دخترانه شیک و باکیفیت",
    price: 250000,
    images: ["/images/girl1.jpg", "/images/girl2.jpg"],
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    sizes: ["S", "M", "L", "XL"],
    reviews: [
      { user: "زهرا", comment: "خیلی عالی بود 👌" },
      { user: "نگین", comment: "جنس خوب، ارسال سریع" },
    ],
  },
  {
    id: "2",
    name: "لباس پسرانه",
    category: "boy",
    description: "لباس راحت و شیک برای پسران",
    price: 200000,
    images: ["/images/boy1.jpg", "/images/boy2.jpg"],
    colors: ["#000", "#555"],
    sizes: ["M", "L"],
    reviews: [],
  },
  {
    id: "3",
    name: "کت پاییزه",
    category: "fall",
    description: "کت گرم و سبک برای پاییز",
    price: 350000,
    images: ["/images/fall1.jpg"],
    colors: ["#795548"],
    sizes: ["M", "L", "XL"],
    reviews: [],
  },
  {
    id: "4",
    name: "تیشرت بهاره",
    category: "spring",
    description: "تیشرت نخی و خنک برای بهار",
    price: 150000,
    images: ["/images/spring1.jpg"],
    colors: ["#ffeb3b", "#4caf50"],
    sizes: ["S", "M", "L"],
    reviews: [],
  },
];
