export const heroSlides = [
  {
    id: 1,
    title: "لباس پاییزه",
    subtitle: "جدیدترین‌ها با بهترین قیمت",
    ctaText: "مشاهده محصولات",
    ctaHref: "#",
    bg: "/imgs/slider/slide5.jpg",
    deco: [
      { src: "/imgs/slider/balloon.png", className: "absolute top-[50px] left-[60px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[60px] right-[80px] w-16 md:w-20", anim: "animate-bounce" },
      { src: "/imgs/slider/balloon2.png", className: "absolute top-[120px] left-[200px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[100px] right-[150px] w-16 md:w-20", anim: "animate-bounce" },
    ],
  },
  {
    id: 2,
    title: "لباس کودک",
    subtitle: "فصل جدید، استایل جدید",
    ctaText: "مشاهده محصولات",
    ctaHref: "#",
    bg: "/imgs/slider/slide3.jpg",
    deco: [
      { src: "/imgs/slider/balloon.png", className: "absolute top-[40px] right-[80px] w-18 md:w-24", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[50px] left-[70px] w-14 md:w-20", anim: "animate-pulse" },
      { src: "/imgs/slider/balloon2.png", className: "absolute top-[120px] left-[150px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[90px] right-[100px] w-16 md:w-22", anim: "animate-bounce" },
    ],
  },
  {
    id: 3,
    title: "لباس کودک",
    subtitle: "فصل جدید، استایل جدید",
    ctaText: "مشاهده محصولات",
    ctaHref: "#",
    bg: "/imgs/slider/slide4.jpg",
    deco: [
      { src: "/imgs/slider/balloon.png", className: "absolute top-[60px] left-[80px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[70px] right-[120px] w-16 md:w-22", anim: "animate-bounce" },
      { src: "/imgs/slider/balloon2.png", className: "absolute top-[140px] left-[200px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[100px] right-[150px] w-16 md:w-20", anim: "animate-bounce" },
    ],
  },
  {
    id: 4,
    title: "لباس کودک",
    subtitle: "فصل جدید، استایل جدید",
    ctaText: "مشاهده محصولات",
    ctaHref: "#",
    bg: "/imgs/slider/slide2.jpg",
    deco: [
      { src: "/imgs/slider/balloon.png", className: "absolute top-[70px] left-[100px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[80px] right-[120px] w-16 md:w-22", anim: "animate-bounce" },
      { src: "/imgs/slider/balloon2.png", className: "absolute top-[150px] left-[250px] w-20 md:w-28", anim: "animate-bounce-slow" },
      { src: "/imgs/slider/balloon3.png", className: "absolute bottom-[120px] right-[160px] w-16 md:w-20", anim: "animate-bounce" },
    ],
  },
];
